# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!


pod 'UMengAnalytics', '~> 3.6.6'



target 'GitHuber' do

end

target 'GitHuberTests' do

end

target 'GitHuberUITests' do

end

