# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


#pod 'UMengAnalytics', '~> 3.6.6'
pod 'Alamofire', '~> 2.0'
pod 'SwiftyJSON', '~> 2.3.2'
pod 'SDWebImage', '~>3.7'

target 'GitHuber' do

end

target 'GitHuberTests' do

end

target 'GitHuberUITests' do

end

