# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'SDWebImage', '~>3.7'
#pod 'YTKNetwork', '~> 0.5.0'
pod 'AFNetworking', '~> 3.0.0'
pod 'MJExtension', '~> 3.0.7'
pod 'MJRefresh', '~> 3.0.8'

target 'RollClient' do

end

target 'RollClientTests' do

end

target 'RollClientUITests' do

end

