# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ScheduleClient' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, ‘8.0’
  pod 'GTSDK', '~> 1.5.0'

  # Pods for ScheduleClient

  target 'ScheduleClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScheduleClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
